### ISSUE TITLE
Fix assertions in Parameters construction

### ISSUE THREAD

**Issue by aversey** [DD2480-group14/Assignment-1#57]
We need to make assertions only about used variables. If A_PTS and B_PTS are not used, we should not check for A_PTS+B_PTS<NUMPOINTS-3.

**Comment by dengty1998** [comment]
Understood, I will pay attention to this in the future.

**Comment by aversey** [comment]
> Understood, I will pay attention to this in the future.

This is about class Parameters, no problem with the code you wrote. =)
